name: build and push docker image to DockerHub when new commit
on:
  push:
    branches: main
  workflow_dispatch:
jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - name: copy repo to vm
        uses: actions/checkout@v4
      - name: login into DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USER }}/streamlit_remove_background:latest
      # - name: build image
      #   run: docker buildx build --platform linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/arm64,linux/arm/v7,linux/arm/v6 -t ${{ secrets.DOCKERHUB_USER }}/streamlit_remove_background:latest .
      # - name: docker push image to registry
      #   run: docker push ${{ secrets.DOCKERHUB_USER }}/streamlit_remove_background:latest